# Generated by Django 3.2.2 on 2021-05-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=122)),
                ('are_they_willing_to_relocate', models.TextField()),
            ],
        ),
    ]
